### ISSUE TITLE
merge into github.com/batocera-linux/batocera.linux ?

### ISSUE THREAD

**Issue by nadenislamarre** [RK3128-CFW/rk3128-cfw.github.io#1] opened 2022-03-14 12:20 UTC
if you want, we can merge into github.com/batocera-linux/batocera.linux

**Comment by acmeplus** [comment] 2022-03-14 13:53
> if you want, we can merge into github.com/batocera-linux/batocera.linux

Yes @nadenislamarre , you read my mind :) 

We haven't had time to reach to you guys about getting this merged. So far 99% of the changes are compatible with batocera main, the only thing that is pending is to merge a lot of build root sdl2 changes that had to be left at 2.0.12 to get the rk3128 to render properly without the need of a dedicated rk3128 libdrm.

Let me know what would be the best approach.

**Comment by nadenislamarre** [comment] 2022-03-14 19:44
1) about the "what" : is there
- https://github.com/RK3128-CFW/batocera.linux/commits/rk3128-cfw
- https://github.com/RK3128-CFW/buildroot/tree/rk3128-cfw

or is there something else ?

2) about the how :
- first point to do is to rebase on master
- second point is to move on sdl2.0.20. i can help. i don't get why all was disabled.

3) remove all the changes done in buildroot. for me, it can be done without these modifications. if one is an issue, ask me.

4) about some details:
i've not understood why there is :
- package/batocera/toolchain/toolchain-optional-linaro-arm

i guess that package/batocera/utils/rkbin
should be renamed package/batocera/boot/rock960-blobs or rockpro64-blobs

i don't get why sdl2 patches where removed : board/batocera/patches/old_sdl2_patches
by the way, sdl2.0.20 should be used now. i can help if necessary to adapt some patches.

some modification like board/batocera/rockchip/rk3128/patches/batocera-emulationstation/001-mixer.patch
should be done differenlty (there is a flag in .mk i guess for this one). in a first run, it is ok.

modifications on package/batocera/core/batocera-system/batocera.conf about volume for all boards is not welcome. if that's an issue, we can add a variable/sed.

changes in buildroot have not to be there.
for me, buildroot should be kept unchanged (and upgraded to last one).
patches goes in batocera.linux/board/batocera/patches
defconfigs in in batocera.linux/defconfig
etc...

a release should be done on batocera master

**Comment by acmeplus** [comment] 2022-03-14 20:40
Some answers below. I agree with most points, I'll work on getting the build synchronized with master and then let you know if we need help figuring out how to solve any problems we may face.

> 1. about the "what" : is there
> 
> * https://github.com/RK3128-CFW/batocera.linux/commits/rk3128-cfw
> * https://github.com/RK3128-CFW/buildroot/tree/rk3128-cfw
> 
> or is there something else ?

Nothing else Batocera-wise. The additional repos are the linux and u-boot repos, and those are also in this space.

> 2. about the how :
> 
> * first point to do is to rebase on master

Agreed, that's part of the reason we have not approached you before. I want to rebase to master and check that everything is still working (it should).

> * second point is to move on sdl2.0.20. i can help. i don't get why all was disabled.

The original firmware used Weston + rockchip drm to work. Retroarch was running on top of weston. The [original repo](https://github.com/Caesar-github/buildroot) (or at least what is closer to it since the rockchip-linux one has disappeared) used drm and some scripts to do things like hdmi/lvds video switching, headphone detection, etc. It also had a dedicated version of libdrm with a rockchip module that we have not migrated.

I tried initially with the latest sdl (2.0.16 when I tried) and there was a segmentation fault that I didn't have to debug, so I went back to the sdl2.0.12 that was working before on the standalone buildroot build.
 
> 3. remove all the changes done in buildroot. for me, it can be done without these modifications. if one is an issue, ask me.

Agreed, the buildroot changes were mostly done to get a buildroot based image that just included the batocera-es and libretro cores. Most likely I'll go rebase to buildroot master and see if anything breaks (other than sdl2).

> 4. about some details:
>    i've not understood why there is :
> 
> * package/batocera/toolchain/toolchain-optional-linaro-arm

It's been a while, but I believe it was added at some point to get the old u-boot to compile.

> i guess that package/batocera/utils/rkbin should be renamed package/batocera/boot/rock960-blobs or rockpro64-blobs

Ok, didn't know the right place to put it, so it makes sense to put it there. Should it be rock3128-blobs?

> i don't get why sdl2 patches where removed : board/batocera/patches/old_sdl2_patches by the way, sdl2.0.20 should be used now. i can help if necessary to adapt some patches.
> 
> some modification like board/batocera/rockchip/rk3128/patches/batocera-emulationstation/001-mixer.patch should be done differenlty (there is a flag in .mk i guess for this one). in a first run, it is ok.

Agreed.

> modifications on package/batocera/core/batocera-system/batocera.conf about volume for all boards is not welcome. if that's an issue, we can add a variable/sed.

Yes, that's a better approach. The volume was modified because the initial volume of the Powkiddy A12 is uncomfortably loud. Where does it make add the variable/sed? during the post-build scripts, or as part of the configuration for that device?

We also added some global.retroarch overrides to get the first build to work. For some reason RA GL driver performance is really poor compared with SDL2 video driver. We have not investigated that yet but we will do that after the rebase is done.
 
> changes in buildroot have not to be there. for me, buildroot should be kept unchanged (and upgraded to last one). patches goes in batocera.linux/board/batocera/patches defconfigs in in batocera.linux/defconfig etc...

Agreed.

Thanks!

**Comment by nadenislamarre** [comment] 2022-03-14 21:32
>> a dedicated version of libdrm 
if needed we can have a separated libdrm package for rockchip, however, probably we can do without it. let's start simple with this specific version => the aim is first to get a working version with b34 + clean buildroot. for all the rest, we'll find solutions.

for sdl2 crashes, with a gdb stack, probably i can fix. let's try first 2.0.20 then if you've issue, i'll help on that point.

"rock3128-blobs" yes. as a general rule, i'm not a psychopate about naming rules, indentation rules etc. i target more on spirit, and maintenance / evolutivity. my favorite book is the cathedral and bazaar, and my sloggan are keep it simple and worst is better.

for the volume, we can do a simple sed in the .mk, but forget it for the moment. it is a simple modification at end.
a basic thing like : https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/core/batocera-splash/batocera-splash.mk#L70

global.retroarch are ok, until you put them in the yml, not batocera.conf.
like here : https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/core/batocera-configgen/configs/configgen-defaults-odroidxu4.yml#L4

**Comment by acmeplus** [comment] 2022-03-16 04:17
@nadenislamarre almost done. Main branch was synchronized with upstream and I've put all the RK3128 changes into  [this branch](https://github.com/RK3128-CFW/batocera.linux/commit/b0770920fced636dd306acc3eba3693ec0f991dc).

This is a summary of where we are:
* SDL2: the issues have disappeared (I suspect the version I had before had some issues). 
* linaro arm compiler: removed
* All changes from buildroot removed. Now uses the default repo from batocera
* The Batocera-emulationstation mixer patch has not been removed yet
* I had to manually disable the compilation of XOW (not compatible because RK3128 kernel is 4.4). For some reason it's ignoring a ``!BR2_PACKAGE_BATOCERA_TARGET_RK3128`` directive in ``package/batocera/core/batocera-system/Config.in``
* I have to reimplement a patch for libcec that sets ``HAVE_LINUX_API=0``. The reason again is the RK3128 kernel is 4.4. I have a temporary patch but it broke moonlight compilation.

* Other issues:
  * Splash screen does not work. It looks like video is not properly initialized before mpv launches.
  * RA performance with GL/KMS driver is bad. Switching to SDL2 driver works well (but it does not support overlays, etc.). A previous version of the firmware (without batocera, just plain buildroot) had a similar issue that disappeared when I enabled Weston and launched Weston first so it used Wayland instead of KMS.

**Comment by nadenislamarre** [comment] 2022-03-16 06:47
nice. that was very quick.
let me check all that to merge.
however i don't find which branch i've to merge (eventually, create a pr from the branch)

just quickly:
for mpv, in case you've not seen, depending on the board, we've to pass some flags : --vo=drm,sdl --hwdec=yes
https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/core/batocera-splash/batocera-splash.mk#L36
for ra, choosing sdl2 is just a way to let sdl2 to init with its default. it is ok, but behind, sdl2 just choose a value. however, i already got that kind of issue where the fix was to change init windows settings (like fullscreen or some flags). However, let it like this, it is ok (but one day, it will possibly come back).

**Comment by acmeplus** [comment] 2022-03-16 14:16
> nice. that was very quick. let me check all that to merge. however i don't find which branch i've to merge (eventually, create a pr from the branch)

I can merge from ``rk3128-cfw/wip-rk3128`` branch to ``rk3128-cfw/main``, and then create a PR against ``Batocera-linux/main``. Let me know if you want me to do that.

> just quickly: for mpv, in case you've not seen, depending on the board, we've to pass some flags : --vo=drm,sdl --hwdec=yes https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/core/batocera-splash/batocera-splash.mk#L36 

Just confirmed that the hwdec option basically breaks mpv. Adding vo=drm,sdl only work albeit very slowly. I need to investigate further because the video splash was working at some point without issues.

Another problem I didn't realize before, S03system-splash does not work either, the fb needs to be initialized. I don't think fbv fails, but that I need to do something before that.

> for ra, choosing sdl2 is just a way to let sdl2 to init with its default. it is ok, but behind, sdl2 just choose a value. however, i already got that kind of issue where the fix was to change init windows settings (like fullscreen or some flags). However, let it like this, it is ok (but one day, it will possibly come back).

I know SDL2 would use any defined SDL_RENDERDRIVER and or SDL_VIDEODRIVER to determine which actual driver to use. I've not tried passing by fullscreen or some other tests, so I'll give it a try. 

However, as you say, it's probably ok for the time being. Performance with SDL2 is perfectly ok.

**Comment by nadenislamarre** [comment] 2022-03-16 14:35
yes, ok. please create the pr. it will be easier to me to be sure i've the right code and i'll comment on it if needed before merging.

**Comment by acmeplus** [comment] 2022-03-18 12:37
@nadenislamarre I'm almost done preparing the PR but I have a question about something that does not work the way I expected. I added [this change](https://github.com/RK3128-CFW/batocera.linux/commit/905848b13a78caa13a8e22eef47f3ab0b4ce7aa7#diff-31b45c495e4ebb14cd1fb49b90ea4c1447d2bfe20eb8c70c0fa85a643a45ff32) in the configgen for rk3128 yml but the change does not seem to update ``batocera.conf``. Isn't that the right way to include those changes?

**Comment by nadenislamarre** [comment] 2022-03-18 21:06
changing configgen-defaults-rk3128.yml doesn't update batocera.conf.
configgen-defaults.yml is the default system configuration for all boards.
configgen-defaults-rk3128.yml overrides configgen-defaults.yml. it can be defined for any board.
batocera.conf just includes the user set parameters. Ideally, initially, this file is empty.

when you start a game in batocera,
it starts configgen,
configgen :
- loads /usr/share/batocera/configgen/configgen-defaults.yml into a dictionnary
- loads /usr/share/batocera/configgen/configgen-defaults-arch.yml to replace values from it
- loads batocera.conf to replace values from it

this is done here :
https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/core/batocera-configgen/configgen/configgen/Emulator.py#L18

if you start a game, exit and check the produced log (log is written only when exiting)
[root@BATOCERA /userdata/system]# cat ~/logs/es_launch_stdout.log 

at top, you get all the values defined before running this game.
in my case for example :
'smooth': True

but batocera.conf is not modified. of course.
batocera.conf is only modified :
- by the user directly
- by es when the user do modifications in the menu

2022-03-13 18:20:38,606 DEBUG (unixSettings.py:70):loadAll Looking for global.* in /userdata/system/batocera.conf
2022-03-13 18:20:38,607 DEBUG (unixSettings.py:70):loadAll Looking for gamecube.* in /userdata/system/batocera.conf
2022-03-13 18:20:38,608 DEBUG (unixSettings.py:70):loadAll Looking for gamecube.folder["/userdata/roms/gamecube"].* in /userdata/system/batocera.conf
2022-03-13 18:20:38,609 DEBUG (unixSettings.py:70):loadAll Looking for gamecube["Mario_Kart-Double_Dash.iso"].* in /userdata/system/batocera.conf
2022-03-13 18:20:38,610 DEBUG (unixSettings.py:70):loadAll Looking for display.* in /userdata/system/batocera.conf
2022-03-13 18:20:38,611 DEBUG (Emulator.py:44):__init__ uimode: Full
2022-03-13 18:20:38,614 DEBUG (unixSettings.py:70):loadAll Looking for gamecube-renderer.* in /userdata/system/batocera.conf
2022-03-13 18:20:38,615 DEBUG (unixSettings.py:70):loadAll Looking for gamecube["Mario_Kart-Double_Dash.iso"]-renderer.* in /userdata/system/batocera.conf
2022-03-13 18:20:38,616 DEBUG (emulatorlauncher:246):start_rom Settings: {'emulator': 'dolphin', 'core': 'dolphin', 'hud_support': True, 'videomode': 'default', 'ratio': '4/3', 'video_threaded': False, 'smooth': True, 'shaderset': 'sharp-bilinear-simple', 'rewind': False, 'bezel': 'consoles', 'forceNoBezel': False, 'video_frame_delay_auto': True, 'ubershaders': 'asynchronous_ubershader', 'hud_custom': 'position=bottom-left,background_alpha=0.9,legacy_layout=false,custom_text=Aladdin\\,back to the past,custom_text=libretro/snes9x', 'videooutput': 'HDMI-1', 'bezel.resize_tattoo': '0', 'hud': 'custom', 'retroarch.menu_driver': 'xmb', 'showFPS': 'false', 'uimode': 'Full', 'emulator-forced': False, 'core-forced': False}
2022-03-13 18:20:38,616 DEBUG (emulatorlauncher:248):start_rom emulator: dolphin, core: dolphin

**Comment by acmeplus** [comment] 2022-03-19 23:13
> changing configgen-defaults-rk3128.yml doesn't update batocera.conf.

Thanks a lot for the detailed explanation.

**Comment by acmeplus** [comment] 2022-03-23 15:03
@nadenislamarre pull request sent: https://github.com/batocera-linux/batocera.linux/pull/5839

**Closed as completed** 2022-03-24 07:35 UTC
